### ISSUE TITLE
Database file not found

### ISSUE THREAD

**Issue by eddya7med** [thermohub/thermofun#14]
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import thermofun.PyThermoFun as PyThermoFun
>>> engine = PyThermoFun.ThermoEngine("Resources/aq17new-format.json")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError:
**********************************************************************
*** Error: File reading error
*** Reason: Database file Resources/aq17new-format.json not found!
*** Location: ...me/eddya7med/thermofun/ThermoFun/Database.cpp:246
**********************************************************************

**Comment by gdmiron** [comment]
This means that it didn't find the database file at the given path `Resources/aq17new-format.json`  - this is a relative path for where your python code is executed. 

If you have `.../myFolder/myPythonFile.py` then the database file should be `.../myFolder/Resources/aq17new-format.json` . 

You can find some demo database files in `thermofun/Resources/databases/` copy them from there to the folder you want to use them.
