### ISSUE TITLE
The link in README https://thermohub.org/thermofun/thermofun/ is a dead link

### ISSUE THREAD

**Issue by yurivict** [thermohub/thermofun#32]

**Comment by gdmiron** [comment]
thanks for pointing this out. Some settings of the website were wrong. The link should work now.

**Comment by yurivict** [comment]
Thanks.

**Comment by yurivict** [comment]
@gdmiron 
Please note that further links on the website itself are dysfunctional.
For example, the link ```gems4/thermosol``` leads to the ```We can't let you see this page``` message.
Same problem for ```gems4/thermohub ```.
